### PR TITLE
Growing Tree Algorithm

### PR DESCRIPTION
**Pull request by AlexRiosJ**
Hello!
I have made some changes on ```Maze.js``` file to add the new ```GrowingTree.js``` file.
For now, it is just behaving as the Recursive Backtracker. (```.pop()```) for selecting the next cell).

**Do not merge yet.**

I wanted also to know how can I do testing. I couldn't test with ```node local.js```.

Regards!

### CODE REVIEW

**Comment by TheWizardBear** [comment]
Hi, looks good so far. 

The only change that will have to be made to the tests is to add `"growingtree"` to the array of algorithms in `main.test.ts`. 

The tests use [Deno](https://deno.land)'s built-in testing framework. I wouldn't worry about testing it yourself, though, as the tests are all very basic at the moment. However, if you want to run them, then you will have to download Deno and run `deno test` from inside the maze_generator folder.

**Comment by AlexRiosJ** [comment]
Thanks for the info!
I'm trying to use the [Deno extension](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) so then the ```main.test.ts``` is not marked with errors.

I didn't see any ```.vscode/settings.json``` would you recomend to add ```.vscode/``` it to the ```.gitignore```?

**Comment by TheWizardBear** [comment]
Yes, sure: go ahead.

**Comment by AlexRiosJ** [comment]
At last I did not updat the ```.gitignore```... Not really needed.
Well, I added the algorithm to the tests and **most important** I changed the way to select and remove the Cell.
It just left to add a function to select the behavior, maybe from the maze settings can be sent another flag that only works with this algorithm.
I'll wait your response to know if you think this is a good implementation 😊

**Comment by AlexRiosJ** [comment]
Nevermind, I came with this solution.
I think now we can discuss on which other selection methods can be added. (newest, oldest, middle and random are already working)
I also added the `behavior` flag (only works with Growing Tree) to choose the selection method in the maze settings.
And finally updated the README to show this new flag and its defaul value.

**Comment by TheWizardBear** [comment]
Thanks for doing this. I have tried it out and it works well. There are just a few small changes  I think you should make (tell me if you disagree):
* Please can you change the default behaviour to `"random"`. This will help distinguish between the recursive backtracker / depth-first search algorithm and the growing tree algorithm.
* Rename `behavior` to something a little more descriptive (perhaps `cellSelectionMethod`). This doesn't matter too much as everything is still unstable so I might change the API a little anyway.
* Throw an error (rather than defaulting when the `behavior` value is not valid.

I think the only thing left to do is add the option for combinations of selection methods, as you mentioned. I think the best way to do this would be to allow `behavior` to be an object with weights for each of the values.

For example:
```js
{
  random: 0.5,
  oldest: 0.25,
  newest: 0.25
}
```
or
```js
{
  middle: 10,
  newest: 40,
}
```

The first one would each time have a 50% chance of randomly selecting the cell, a 25% chance of selecting the oldest cell and a 25% chance of selecting the newest cell.

For the second one it would be 20% for middle and 40% for newest.


Also, I'm

**Comment by AlexRiosJ** [comment]
Excellent! I'm on it.
For the "behavior" object the second example I assume that is %20 and %80 respectively, right?
Should I need to throw an error also when some property of the object is invalid or just ignore?

**Comment by TheWizardBear** [comment]
Whoops, that's what I meant.

>  Should I need to throw an error also when some property of the object is invalid or just ignore?

I think maybe throw an error if there are no valid properties and if there are some invalid ones as well as some valid ones, just ignore the invalid ones?

**Comment by AlexRiosJ** [comment]
I think now is working after making the suggested changes.

- [x] Changed flag name.
- [x] Added options where `random` is the default and you can add more options with any type of weights (It takes the sum of all and calculates the probability).
- [x] Added `throw` error when a `cellSelectionMethod` is invalid (ignoring when there is at least one valid).
- [x] Updated README regarding these changes (fell free to modify it)

Please test it and tell me if you think is correct.

**Comment by AlexRiosJ** [comment]
I was checking the code and there are two things that remain:
- The `throw "message"` syntax, I think is wrong (correct me if not) but I think should be `throw Error("message")`.
- Throw an error if some weight is less or equal than 0.

**Comment by TheWizardBear** [comment]
It works well! I have a few minor changes I'd like to make as well but I think it will probably be easier if I just merge this now and make the changes myself, as they are all very small. I will also make the changes you suggested as well.

Thank you! This has been great. I'll add a `hacktoberfest-accepted` tag as well, in case you are doing that.

**Comment by TheWizardBear** [comment]
Fixes #2

**Pull request merged**
